### ISSUE TITLE
是的，它出现了很多问题

### ISSUE THREAD

**Issue by laowang1026** [JordyZomer/autoSubTakeover#5]
![image](https://user-images.githubusercontent.com/45323129/68923453-5551f480-07b9-11ea-9ad3-cdd952b2a5ad.png)
![image](https://user-images.githubusercontent.com/45323129/68923511-71ee2c80-07b9-11ea-9f00-03adb080eeb9.png)

**Comment by JordyZomer** [comment]
Hey @laowang1026 ! It seems that you are using an incompatible python version, it will work with python 3.5+ I hope this answers your problems. :)

**Comment by laowang1026** [comment]
我使用的是python3.7

**Comment by JordyZomer** [comment]
@laowang1026 the picture says 2.7.16, the errors looks like an incorrect version too so, are you sure?
